SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE rating_mpa RESTART IDENTITY;
TRUNCATE TABLE genre RESTART IDENTITY;
TRUNCATE TABLE films RESTART IDENTITY;
TRUNCATE TABLE genres RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE friends RESTART IDENTITY;
TRUNCATE TABLE likes RESTART IDENTITY;
TRUNCATE TABLE director RESTART IDENTITY;
TRUNCATE TABLE directors RESTART IDENTITY;
TRUNCATE TABLE reviews RESTART IDENTITY;
TRUNCATE TABLE reviews_likes RESTART IDENTITY;
TRUNCATE TABLE reviews_dislikes RESTART IDENTITY;
TRUNCATE TABLE feed RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;

INSERT INTO rating_mpa (rating)
VALUES ('G'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');

INSERT INTO genre (name)
VALUES ('Комедия'),
       ('Драма'),
       ('Мультфильм'),
       ('Триллер'),
       ('Документальный'),
       ('Боевик');
